### ISSUE TITLE
RazorEngineCompiledTemplate.Run() can hang

### ISSUE THREAD

**Issue by leshy84** [adoconnection/RazorEngineCore#15]
Hallo,

currently there is only RazorEngineCompiledTemplate.Run() with a strange code:
`instance.ExecuteAsync().Wait();`

It can lead to hang.
Please provide/replace with async version of the method.

**Comment by adoconnection** [comment]
Sure

**Comment by wdcossey** [comment]
I did this a few days ago, I will do a PR this evening.

RazorEngine.cs
```
Task<RazorEngineCompiledTemplate<T>> CompileAsync<T>(...)
Task<RazorEngineCompiledTemplate> CompileAsync(..)
```

RazorEngineCompiledTemplate.cs
```
Task<RazorEngineCompiledTemplate> LoadFromFileAsync(...)
Task<RazorEngineCompiledTemplate> LoadFromStreamAsync(...)
Task SaveToStreamAsync(...)
Task SaveToFileAsync(...)
Task<string> RunAsync(...)
```

RazorEngineCompiledTemplateT.cs
```
Task<RazorEngineCompiledTemplate<T>> LoadFromFileAsync(...)
Task<RazorEngineCompiledTemplate<T>> LoadFromStreamAsync(...)
Task SaveToStreamAsync(...)
Task SaveToFileAsync(...)
Task<string> RunAsync(...)
```

The synchronous methods call the asynchronous with `Async(...).GetAwaiter().GetResult()`;

Since this is for .Net Standard 2.0, you can probably drop the synchronous methods at some point, I left them in purely for backwards compatibility.

**Comment by wdcossey** [comment]
https://github.com/adoconnection/RazorEngineCore/pull/16

**Comment by adoconnection** [comment]
@wdcossey great!
nuget version 2020.5.1 ready
https://www.nuget.org/packages/RazorEngineCore
