### ISSUE TITLE
Template Base / static typing

### ISSUE THREAD

**Issue by roja** [adoconnection/RazorEngineCore#7]
Would it be possible to have a template base, as with various other Razor engines, to allow the model passed in to be statically typed?

i.e.

https://github.com/toddams/RazorLight#enable-intellisense-support
https://antaris.github.io/RazorEngine/IntellisenseAndResharper.html

**Comment by adoconnection** [comment]
It is there, though the usage is a little bit different: you have to specify template base type + model type instead of model type only. It is much cooler because you are free to add any extra helpers to template. I'll write WIKI on this topic soon.

```cs
string content = "Hello @Model.Name";

// yeah, heavy definition
RazorEngineCompiledTemplate<RazorEngineTemplateBase<TestModel>> template = razorEngine.Compile<RazorEngineTemplateBase<TestModel>>(content);

string result = template.Run(instance =>
{
    instance.Model = new TestModel()
    {
        Name = "Hello",
        Items = new[] {3, 1, 2}
    };
});

Console.WriteLine(result);
```

Make sure to update to 
`Install-Package RazorEngineCore -Version 2020.3.3`
